# Generated by Django 3.2.9 on 2022-02-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Full_name', models.CharField(max_length=60, verbose_name='enter full name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='enter valid email')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='enter phone number')),
                ('sign_up_as', models.CharField(choices=[('Donor', 'Donor'), ('Donee', 'Donee')], max_length=20)),
                ('Organization', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=60, verbose_name='Organization')),
                ('donee_name', models.CharField(blank=True, max_length=50, verbose_name='Enter name of you donee organization')),
                ('donee_category', models.CharField(choices=[('Childrens Home', 'Childrens Home'), ('Eldrey Shelter', 'Eldrey Shelter'), ('Street Families', 'Street Families')], max_length=50, verbose_name='Donee category')),
                ('facebook', models.CharField(blank=True, max_length=300, verbose_name='Facebook')),
                ('no_individuals', models.IntegerField(blank=True, null=True)),
                ('twitter', models.CharField(blank=True, max_length=300, verbose_name='Twitter')),
                ('website', models.CharField(blank=True, max_length=300, verbose_name='Website')),
                ('location', models.CharField(max_length=40, verbose_name=' Enter your current location')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
