# Generated by Django 3.2.9 on 2022-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0003_alter_allusers_donee_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allusers',
            name='Organization',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization'), ('               ', '               ')], max_length=60, verbose_name='Organization'),
        ),
    ]
