# Generated by Django 3.2.9 on 2022-02-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('Full_name', models.CharField(max_length=60, verbose_name='enter full name')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='enter valid email')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='enter phone number')),
                ('Organization', models.CharField(choices=[('Individual', 'Individual'), ('Organization', 'Organization')], max_length=60, verbose_name='Organization')),
                ('location', models.CharField(max_length=40, verbose_name=' Enter your current location')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('last_login', models.DateField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
