# Generated by Django 3.2.9 on 2022-02-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Login_Register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='no_individuals',
            field=models.IntegerField(),
        ),
    ]
