# Generated by Django 4.0.2 on 2022-02-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Consumer_Login_Register', '0002_alter_consumer_no_individuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='Twitter',
            field=models.CharField(max_length=300, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='Website',
            field=models.CharField(max_length=300, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='facebook',
            field=models.CharField(max_length=300, null=True, verbose_name='facebook'),
        ),
    ]
